default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: jisr
  password: jisr
  host: localhost

development:
  <<: *default
  database: matrial_dashboard_development

test:
  <<: *default
  database: matrial_dashboard_test
